/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/60SNXWL3YzW
 */
import { Label } from "~/components/ui/label"
import { Input } from "~/components/ui/input"
import { Button } from "~/components/ui/button"
import { Separator } from "~/components/ui/separator"
import Link from "next/link"
import { LoginWithGoogleButton } from "./login-with-google-button"

export function LoginForm() {
  return (
    <div className="flex flex-col items-center space-y-4">
      <div className="w-full max-w-sm space-y-4">
        <div className="space-y-2 text-center">
          <h1 className="text-3xl font-bold">Login</h1>
          <p className="text-gray-500 dark:text-gray-400">Enter your email below to login to your account</p>
        </div>
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="m@example.com" required type="email" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input id="password" required type="password" />
          </div>
          <Button className="w-full" type="submit">
            Sign In
          </Button>
          <Separator className="my-8" />
          <LoginWithGoogleButton />
          <Separator className="my-8" />
          <Link className="w-full" href="/signup">
            Create an account
          </Link>
        </div>
      </div>
    </div>
  )
}
