/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qlpHchM4Fkw
 */
import { Label } from "~/components/ui/label"
import { Input } from "~/components/ui/input"
import { Button } from "~/components/ui/button"
import { Separator } from "~/components/ui/separator"
import Link from "next/link"
import { LoginWithGoogleButton } from "./login-with-google-button"

export function SignupForm() {
  return (
    <div className="mx-auto max-w-sm space-y-6">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">Sign Up</h1>
        <p className="text-gray-500 dark:text-gray-400">Enter your information to create an account</p>
      </div>
      <div className="space-y-2">
        <Label htmlFor="email">Email</Label>
        <Input id="email" placeholder="praseem@example.com" required />
      </div>
      <div className="space-y-2">
        <Label htmlFor="password">Password</Label>
        <Input id="password" required type="password" />
      </div>
      <div className="space-y-2">
        <Label htmlFor="confirm-password">Confirm Password</Label>
        <Input id="confirm-password" required type="password" />
      </div>
      <Button className="w-full">Sign Up</Button>
      <Separator className="my-8" />
      <div className="space-y-4">
        <LoginWithGoogleButton />
        <div className="mt-4 text-center text-sm">
          Already have an account?
          <Link className="underline" href="#">
            Login
          </Link>
        </div>
      </div>
    </div>
  )
}
